# require 'polevault'
require 'polevault/migration'

class TestMigration < Polevault::Migration
  def migrate
    # NOTE: Within this class you have access to the `client`
    # instance variable, which will have access to setup your
    # Vault node through the root token generated by init. See
    # https://github.com/hashicorp/vault-ruby for API docs
    #
    # vault.logical.write('secret/test', value: "Some Value")
    vault.logical.write('secret/test', value: "Hooray!")
  end
end
