require 'polevault/migration'
require 'erb'

class NewMigration < Polevault::Migration
  def migrate
    # NOTE: Within this class you have access to the following variables:
    #
    # vault: Vault::Client instance configured with config
    #   This which will have access to setup your
    #   Vault node through the root token generated by init. See
    #   https://github.com/hashicorp/vault-ruby for API docs
    # config: Figly::Settings hash that has config accessible via dot operator.
    #   see http://github.com/onetwopunch/figly for details
    # kv: The kv store you specified in your config with methods read/write.
    #
    # i.e.
    # vault.logical.write('secret/test', value: config.custom.secret_value)

    vault.sys.enable_auth('github', 'github')
    vault.logical.write('auth/github/config', organization: 'hashicorp')
    vault.logical.write('auth/github/map/teams/ops', value: 'ops')

    # You can use ERB to inject values into policies
    @path = config.custom_path
    limited_template = File.read(File.join(Polevault.root, 'test/fixtures/policies/limited_policy.hcl.erb'))
    limited_policy = ERB.new(limited_template).result(binding)
    vault.sys.put_policy("limited", limited_policy)
  end
end
